### ISSUE TITLE
clone_wp_site.py: App config not set

### ISSUE THREAD

**Issue by cvn** [opalstack/opalstack-python#10]
An app created by clone_wp_site.py will have an "empty" config.

Some consequences:

- The app is on PHP 7.3.33, which causes Wordpress to display a warning.
- "Manage Site URL" is missing.

I expected the script to clone the config from the src app, or use defaults that matched dashboard-created apps.

1. Would you consider updating clone_wp_site.py to show how to clone the src config?
2. Is it practical for the create_one function, or the installer scripts themselves, to set defaults when values are not provided?

Thanks,
Chad

<img width="275" alt="Screenshot of empty config" src="https://user-images.githubusercontent.com/774864/193393987-63b29660-e359-420a-afec-b37cff4d9aaa.png"> <img width="275" alt="Screenshot of Wordpress warning" src="https://user-images.githubusercontent.com/774864/193394034-06e23056-3617-41d2-8148-b71fb68e5b0b.png"> <img width="275" alt="Screenshot of Manage Site URL" src="https://user-images.githubusercontent.com/774864/193396060-1c5ab8e9-24a9-4033-b25c-dfbb6338e09b.png">

For reference, this is the current app creation code.

https://github.com/opalstack/opalstack-python/blob/13642f1e74de74daa38e8c5ed97cfe432494eeee/examples/clone_wp_site.py#L108-L115

**Comment by yqdv** [comment]
@cvn 
Hello Chad,
Apologies for the delay, and thanks a lot for the suggestions and bug reports. We appreciate it!

> Would you consider updating clone_wp_site.py to show how to clone the src config?

Yes, certainly. I'll incorporate this (along with fixes for the other issues) and push a new release.

> Is it practical for the create_one function, or the installer scripts themselves, to set defaults when values are not provided?

Practical, yes, but it would run counter to the design philosophy behind Opalstack's backend (including API). The backend has a convention of being explicit, which in turn has helped to identify usage bugs that would have been masked by defaults. The user interface, on the other hand, takes the opposite approach: providing as many defaults as necessary to streamline the experience from the perspective of a new user. 

There _is_ a concept of an "API UI" which implements what you are suggesting- a predominantly user-friendly API layer on top of a Core API, but that comes with a definite risk of feature-creep. Usually, a good example (with relevant options specified) is the best of both worlds.

**Comment by cvn** [comment]
Thank you, @yqdv. I appreciate the thoughtful response.

What enables the "Manage Site URL" UI? It feels surprising that the opalstack install.sh script doesn't enable the UI by default.

**Comment by yqdv** [comment]
@cvn 

This is now fixed in commit https://github.com/opalstack/opalstack-python/commit/a766831be5de311a1c302d4c790cee8ffdc2eeb6 . The script now clones the src app config.

To answer your questions:

- What enables the "Manage Site URL" UI?

Applications have configuration options documented at https://my.opalstack.com/api/v1/doc/#/app/app_create
(see the `json` field in the `Responses` schema).

In the REST API, this field is a JSON-encoded string (hence the name), and is represented in opalstack-python as a dict.
The app config option that controls "Manage Site URL" is the `auto_site_url` field of the app config.
Similarly, the PHP version is controlled by the `php_version` config option.

In order to set these on an app at creation, you could do something like:
```python3
created_app = opalapi.apps.create_one({
    'name': DST_APP_NAME,
    'osuser': dst_osuser['id'],
    'type': 'APA',
    'installer_url': 'https://raw.githubusercontent.com/opalstack/installers/master/core/wordpress/install.sh',
    'json': {
        'php_version': 81,
        'auto_site_url': True,
    }
})
```

In the **clone_wp_app.py** update, I went ahead and copied the entire source app config and then apply it to the newly-created app. This includes `php_version` and `auto_site_url` as well as other options like `gzip`, `fpm_max_children`, etc. It's also forward-compatible to any new config options added in the future.

- It feels surprising that the opalstack install.sh script doesn't enable the UI by default.

I cannot really speak to the default as I am not the author or maintainer of the app installer scripts. Perhaps it would be better if the install.sh script defaulted to enabling site_url management. On the other hand, that would constitute a breaking change for anyone relying on the existing behavior, so it doesn't seem prudent to change it now without a compelling reason. The setting is easily controlled through the app options, after all.

**Comment by cvn** [comment]
Thank you again, @yqdv! I just cloned an app, and it went flawlessly.

I want to clarify my point about the "Manage Site URL" UI. It's the lack of the interface elements that is surprising, not the default value. When no config is provided, the UI [doesn't appear](https://user-images.githubusercontent.com/774864/193393987-63b29660-e359-420a-afec-b37cff4d9aaa.png) in the app settings.

I have a good idea about why this is the case, now, but it was a surprise that an app created with the install script did not have the same settings available (visible) as an app created in the dashboard. This is similar to my surprise about the default values, but it's less obvious how to fix this issue.

**Comment by yqdv** [comment]
@cvn 
Ah, thanks for clarifying. I see what you mean. I think the reason for this problem is that a Wordpress application is really just a "PHP" application type once installation has completed. So, for an existing application, the system does not "know" that this app option is applicable- since it's not applicable in general to all PHP apps.

However, this reasoning is speculation on my part. I am a python and golang back-end developer, so I have never worked on the Opalstack UI. I don't even know enough to be dangerous when it comes to user interface / web front-end development.
